### ISSUE TITLE
Your commented-out tests work!

### ISSUE THREAD

**Issue by rub1e** [fac-15/casual-sports#121]
From what I can see, your commented out database tests work for the most part - you just need to tweak them to match your linting rules (`prefer-arrow-function`)

That said, your `error` tests aren't working, and that's pretty important - you need to know if errors are thrown when they're supposed to be, otherwise your tests might be passing by accident

**Comment by zurda** [comment]
Thanks @rubie, but actually these tests aren't arrow functions because they were commented out before we added the linter... They were passing locally for us as well, but they were failing once we pushed to Travis. We're not sure why.

**Comment by rub1e** [comment]
Check out #125 - you're so close!

**Comment by zurda** [comment]
Oh! We sure will 😊 thanks!
