### ISSUE TITLE
numToString failing tests

### ISSUE THREAD

**Issue by rub1e** [fac-15/casual-sports#124]
Your numToString tests are failing for an amusingly ironic reason... :smile_cat: 

If you fix it (with one line), you'll get this:

![image](https://user-images.githubusercontent.com/11595920/51440880-7d6ce600-1cc3-11e9-95fa-43d5b5e89642.png)

Which will make you happy

**Comment by tantsandras** [comment]
Hahaha yes we saw it now! Something happened when we merged on friday lol. It's fixed now! Thanks Rubie
